[WIP] 108 Migrate tests to junit5 and testcontainers
AxonFramework/extension-kafka pull request #111
Opened 2021-02-12 11:57 UTC by lfgcampos

This PR has a lot of work around testing.

It migrates every test to junit5 and also introduce `@Testcontainers` approach instead of `EmbeddedKafka`.

Fixes #108.

2021-02-12 11:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/AxonFramework/extension-kafka?pullRequest=111) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/AxonFramework/extension-kafka?pullRequest=111) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: sandjelkovic<br/>:x: lfgcampos<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/AxonFramework/extension-kafka?pullRequest=111) it.</sub>

2021-02-12 14:49 UTC, sandjelkovic reviewed
Minor things are left, like javadoc and cleanup. Otherwise looks great 👍

2021-02-12 14:49 UTC, sandjelkovic commented on kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/util/KafkaContainerCluster.java
> +        if (brokersNum < 0) {
```suggestion
        if (brokersNum <= 0) {
```

2021-02-12 14:49 UTC, sandjelkovic commented on kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/util/KafkaContainerCluster.java
> +        if (internalTopicsRf < 0 || internalTopicsRf > brokersNum) {
```suggestion
        if (internalTopicsRf <= 0 || internalTopicsRf > brokersNum) {
```

2021-02-12 14:49 UTC, sandjelkovic commented on kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/util/KafkaContainerClusterTest.java
> +                                                                                           3,
Nit: Weird formatting

2021-02-12 14:49 UTC, sandjelkovic commented on kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/util/KafkaAdminUtils.java
> +    public static void createTopics(String bootstrapServer, String... topics) {
Missing Javadocs on public methods. Applies for all public method in this class

2021-02-12 14:49 UTC, sandjelkovic commented on kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/util/KafkaContainerClusterTest.java
> +@Testcontainers
Missing Javadoc

2021-02-12 14:49 UTC, sandjelkovic commented on kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/util/KafkaContainerTest.java
> +public abstract class KafkaContainerTest {
Missing Javadoc

2021-02-12 14:49 UTC, sandjelkovic commented on kafka/pom.xml
>          <spring-kafka-test.version>2.6.5</spring-kafka-test.version>
Cleanup: `spring-kafka-test` dependency is not needed anymore

2021-02-12 14:49 UTC, sandjelkovic commented on kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/consumer/AsyncFetcherTest.java
> +        KafkaAdminUtils.createTopics(KAFKA_CONTAINER.getBootstrapServers(), TEST_TOPIC);
Nit: `KAFKA_CONTAINER.getBootstrapServers()` can be moved to `KafkaContainerTest`as a base method that the tests can use without caring about the Container at all

2021-02-12 14:49 UTC, sandjelkovic commented on kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/producer/DefaultProducerFactoryClusteringTest.java
> +        KafkaAdminUtils.createTopics(KAFKA_CLUSTER.getBootstrapServers(), TOPIC);
Nit: `KAFKA_CLUSTER.getBootstrapServers()` can be moved to `KafkaContainerClusterTest` as a base method that the tests can use without knowing about the Container or Cluster at all

2021-02-12 16:27 UTC, smcvb requested changes
Several relatively small arguments to go over prior to approval.

2021-02-12 16:27 UTC, smcvb commented on kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/util/KafkaContainerCluster.java
> +            e.printStackTrace();
Is printing the stack trace sufficient? Shouldn't we throw the exception too, or log it? 
I'd assume the test set up should fail in absence of any of the desired containers.

2021-02-12 16:27 UTC, smcvb commented on kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/util/KafkaContainerCluster.java
> +        Unreliables.retryUntilTrue(30, TimeUnit.SECONDS, () -> {
Curious: is this because ZooKeeper is unreliable during start-up? Or are you guys uncertain as this has been copied from a different location? ;-)

2021-02-12 16:27 UTC, smcvb commented on kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/util/KafkaContainerClusterTest.java
> + * A cluster of kafkas using test container.
I'd more so anticipate something like this:

```suggestion
 * A {@link KafkaContainerCluster} set up by using {@link Testcontainers.
```

And similarly, some author tags. Grab those creds :p

2021-02-12 16:27 UTC, smcvb commented on kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/util/KafkaContainerTest.java
> + * A single node of kafka using test container.
Same argumentation on this guy as I placed on the `KafkaContainerClusterTest` class.

2021-02-12 16:27 UTC, smcvb commented on kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/producer/DefaultProducerFactoryClusteringTest.java
> +//    @Disabled("clustering is needed")
I think this comment can be removed.

2021-02-12 16:57 UTC, lfgcampos commented on kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/util/KafkaContainerCluster.java
> + * Copied from https://github.com/testcontainers/testcontainers-java/blob/master/examples/kafka-cluster/src/test/java/com/example/kafkacluster/KafkaContainerCluster.java
I haven't made any adjustment so far and there is no author on the original class.

2021-02-12 16:59 UTC, lfgcampos commented on kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/util/KafkaAdminUtils.java
> +     * Method responsible for creating partitions on given kafka and topics.
Changed slightly different, also including `@code` for the `bootstrapServer` variable.

2021-02-15 09:40 UTC, smcvb commented on kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/util/KafkaContainerCluster.java
> + * Copied from https://github.com/testcontainers/testcontainers-java/blob/master/examples/kafka-cluster/src/test/java/com/example/kafkacluster/KafkaContainerCluster.java
That definitely complicates things. Isn't the original commiter in the commit messages of the class you guys copied?

2021-02-15 09:48 UTC, smcvb commented on kafka-spring-boot-autoconfigure/src/test/java/org/axonframework/extensions/kafka/SubscribingProducerIntegrationTest.java
> -        assertThat(Thread.currentThread().getId()).isEqualTo(threadIdCaptor.getThreadId());
I believe we can remove the `public` modifier from this method and from the test class. Or is this not an option because it's a `@SpringBootTest`?

2021-02-15 15:49 UTC, smcvb commented on kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/util/KafkaContainerCluster.java
> +    private final GenericContainer<?> zookeeper;
Issue resolved through video chat - this approach is taken as it's a copied version from test containers themselves.

2021-02-15 15:49 UTC, smcvb approved these changes
My concerns have been addressed, hence approving.

2021-02-15 16:00 UTC, merged